* octool — building Opencast with style

[[https://travis-ci.org/pmiddend/octool.svg?branch=master][https://travis-ci.org/pmiddend/octool.svg?branch=master]]

** What is it?

It’s a tool to help you build [[https://opencast.org][Opencast]]. If you don’t know what Opencast is, please do not read on.

What’s the problem building Opencast, you say? It’s nothing major, really, but…

- it has a /lot/ of stuff going to standard output and standard error.
- you have to remember certain settings, like “how do I turn off tests again?”
- building something “relative to a certain git version” is not possible“

and a few other things that just annoyed me after a while, so I wrote this tool.

** Installation

Out of sheer lazyness (pun intended), I currently depend wholly on the [[https://nixos.org][Nix]] package manager to build it. With it, however, building it is trivial:

#+begin_example
nix-build
#+end_example

Without it…well, it’s not possible.

** Usage

Your working directory has to be the Opencast root directory. Then just call it, possibly with =--help= to discover its options. They should be self-explanatory:

#+begin_example
Usage: octool [--relative-to ARG] [--rebuild ARG] [--create-ca ARG]
              [--target-assembly ARG] [--clean] [--stdout] [--show-last-log]
              [--yes] [--no] [--no-checkstyle] [--no-tests]

Available options:
  --relative-to ARG        rebuild only modules changed since the version
                           specified
  --rebuild ARG            rebuild this specific modules (and dependents
                           thereof)
  --create-ca ARG          create a capture agent on the locally running
                           instance
  --target-assembly ARG    use the specified assembly instead of develop
  --clean                  clean before build
  --stdout                 output stdout, too
  --show-last-log          show last log
  --yes                    say "yes" to everything
  --no                     say "no" to everything
  --no-checkstyle          disable checkstyle
  --no-tests               disable tests
  -h,--help                Show this help text
#+end_example
